### ISSUE TITLE
it seems like the customer header not working by use method setDataSource ,please fix it ,thanks

### ISSUE THREAD

**Issue by kyriej** [wseemann/FFmpegMediaMetadataRetriever#264] opened 2022-10-19 15:02 UTC

**Comment by wseemann** [comment] 2022-10-20 16:35
Hi @kyriej, can you post a code example outlining your issue. I'm not sure exactly what the issue is based on your description. Thanks!

**Comment by kyriej** [comment] 2022-10-20 16:48
Hi , the code like this

var retriever = FFmpegMediaMetadataRetriever();
val header = HashMap<String , String>();
header.put("key1","val1");
var path = "https://example.com/test.mp4";
retriever.setDataSource(path , header);

it seems like the heder not include in the player request

===================================

    public void setDataSource(String uri,  Map<String, String> headers)
            throws IllegalArgumentException {
        int i = 0;
        String[] keys = new String[headers.size()];
        String[] values = new String[headers.size()];
        for (Map.Entry<String, String> entry: headers.entrySet()) {
            keys[i] = entry.getKey();
            values[i] = entry.getValue();
            ++i;
        }
        _setDataSource(uri, keys, values);
    }

    private native void _setDataSource(
        String uri, String[] keys, String[] values)
        throws IllegalArgumentException;

**Comment by wseemann** [comment] 2022-10-20 16:52
I'll take a look, thank you @kyriej

**Comment by wseemann** [comment] 2023-01-30 01:31
This issue has been fixed in version 1.0.19.

**Closed by wseemann** 2023-01-30 01:31 UTC
