### ISSUE TITLE
Can't handle spaces in paths

### ISSUE THREAD

**Issue by manuelpaulo** [wseemann/FFmpegMediaMetadataRetriever#145] opened 2017-03-31 17:56 UTC
Spaces in paths makes it crash.  URLEncoder.encode to utf-8 didn't help either.

**Comment by wseemann** [comment] 2021-12-24 06:45
I'm unable to reproduce this issue using version [1.0.16](https://github.com/wseemann/FFmpegMediaMetadataRetriever/releases/tag/v1.0.16). Closing out this issue.

**Closed by wseemann** 2021-12-24 06:45 UTC
